version: '3.8'

services:
  db:
    image: postgres:16
    container_name: polars_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - ./src/generate_data.sql:/docker-entrypoint-initdb.d/init.sql

  etl_app:
    image: polars-env:latest
    container_name: polars_python
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/etl_db
      - POLARS_UNKNOWN_EXTENSION_TYPE_BEHAVIOR=load_as_storage
    command: tail -f /dev/null